name: Dependency Review

on:
  pull_request:
    paths:
      - "extension-files/**/package.json"
      - "extension-files/**/yarn.lock"
      - "iframe-frontend/package.json"
      - "iframe-frontend/yarn.lock"

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
