name: CI-Iframe

on:
  push:
    paths:
      - 'iframe-frontend/**'
      - '.github/workflows/iframe-ci.yml'
    branches:
      - "**"
  pull_request:
    paths:
      - 'iframe-frontend/**'
      - '.github/workflows/iframe-ci.yml'

permissions:
  contents: read

env:
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iframe-frontend
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: 'iframe-frontend/yarn.lock'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Validate, lint, and build
        run: yarn verify
