name: Publish SDK
on:
  workflow_run:
    workflows: [CI-SDK]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: '22'

defaults:
  run:
    working-directory: extension-files/bringweb3-sdk

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Debug directory structure
        run: |
          pwd
          ls -la
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'extension-files/bringweb3-sdk/yarn.lock'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@57dd5be9ba8852146913fabe3c122b219bb90fa2 # v1.4.9
        with:
          publish: yarn release
          cwd: "${{ github.workspace }}/extension-files/bringweb3-sdk"
          commit: "chore(release): version SDK package"
          title: "chore(release): version SDK package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
